In [1]:
# imports
import pandas as pd
import numpy as plt 
import matplotlib.pyplot as plt

import requests

## Functions

In [69]:
# formatting json data derived from this source: 'https://stackoverflow.com/questions/47577927'
# api 
def data_puller(starting_page, ending_page, url):
    ''' 
        Pulls .json data from API, from specified page range, with given url
        and formats it all into one dataframe.
    '''
    
    headers = {
        "X-RapidAPI-Key": "1201ae780cmsh7393c8d2372c07dp148e7fjsn029918f1d16c",
        "X-RapidAPI-Host": "car-api2.p.rapidapi.com"
    }

    data = []
    for page in range(starting_page, ending_page + 1):
        querystring = {"verbose":"yes","direction":"asc","sort":"id","page":page}
        response = requests.get(url, headers=headers, params=querystring)
        
        if response.status_code == 200:
            print(f"Connected to page {page} of {url}")
            page_data = response.json()['data']
            data.extend(page_data)
            
        else:
            print(f"Response status: {response.status_code}")
    
    return pd.DataFrame(data)

### pulling drivetrain and transmission types

In [71]:
engine_url = "https://car-api2.p.rapidapi.com/api/engines"
data_puller(1, 10, engine_url)

Connected to page 1 of https://car-api2.p.rapidapi.com/api/engines
Connected to page 2 of https://car-api2.p.rapidapi.com/api/engines
Connected to page 3 of https://car-api2.p.rapidapi.com/api/engines
Connected to page 4 of https://car-api2.p.rapidapi.com/api/engines
Connected to page 5 of https://car-api2.p.rapidapi.com/api/engines
Connected to page 6 of https://car-api2.p.rapidapi.com/api/engines
Connected to page 7 of https://car-api2.p.rapidapi.com/api/engines
Connected to page 8 of https://car-api2.p.rapidapi.com/api/engines
Connected to page 9 of https://car-api2.p.rapidapi.com/api/engines
Connected to page 10 of https://car-api2.p.rapidapi.com/api/engines

,id,make_model_trim_id,engine_type,fuel_type,cylinders,size,horsepower_hp,horsepower_rpm,torque_ft_lbs,torque_rpm,valves,valve_timing,cam_type,drive_type,transmission,make_model_trim
0,1,1,gas,premium unleaded (recommended),I4,1.5,200,6000.0,192.0,1800.0,16.0,Variable,Double overhead cam (DOHC),front wheel drive,continuously variable-speed automatic,"{'id': 1, 'make_model_id': 1, 'year': 2023, 'n..."
1,2,2,gas,premium unleaded (recommended),I4,5.0,200,6000.0,192.0,1800.0,16.0,Variable,Double overhead cam (DOHC),front wheel drive,continuously variable-speed automatic,"{'id': 2, 'make_model_id': 1, 'year': 2023, 'n..."
2,3,3,gas,premium unleaded (recommended),I4,5.0,200,6000.0,192.0,1800.0,16.0,Variable,Double overhead cam (DOHC),front wheel drive,continuously variable-speed automatic,"{'id': 3, 'make_model_id': 1, 'year': 2023, 'n..."
3,4,4,gas,premium unleaded (recommended),I4,5.0,200,6000.0,192.0,1800.0,16.0,Variable,Double overhead cam (DOHC),front wheel drive,6-speed manual,"{'id': 4, 'make_model_id': 1, 'year': 2023, 'n..."
4,5,5,gas,premium unleaded (recommended),V6,3.5,290,6200.0,267.0,4700.0,24.0,Variable,Single overhead cam (SOHC),front wheel drive,10-speed shiftable automatic,"{'id': 5, 'make_model_id': 2, 'year': 2023, 'n..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,996,gas,regular unleaded,I4,2.7,310,5600.0,348.0,1500.0,16.0,Variable,Double overhead cam (DOHC),rear wheel drive,8-speed shiftable automatic,"{'id': 996, 'make_model_id': 164, 'year': 2022..."
996,997,997,gas,regular unleaded,I4,2.7,310,5600.0,348.0,1500.0,16.0,Variable,Double overhead cam (DOHC),four wheel drive,8-speed shiftable automatic,"{'id': 997, 'make_model_id': 164, 'year': 2022..."
997,998,998,gas,regular unleaded,I4,2.7,310,5600.0,348.0,1500.0,16.0,Variable,Double overhead cam (DOHC),rear wheel drive,8-speed shiftable automatic,"{'id': 998, 'make_model_id': 164, 'year': 2022..."
998,999,999,gas,regular unleaded,I4,2.7,310,5600.0,348.0,1500.0,16.0,Variable,Double overhead cam (DOHC),rear wheel drive,8-speed shiftable automatic,"{'id': 999, 'make_model_id': 164, 'year': 2022..."
999,1000,1000,gas,regular unleaded,I4,2.7,310,5600.0,348.0,1500.0,16.0,Variable,Double overhead cam (DOHC),four wheel drive,8-speed shiftable automatic,"{'id': 1000, 'make_model_id': 164, 'year': 202..."

### pulling body type

In [72]:
body_url = "https://car-api2.p.rapidapi.com/api/bodies"
data_puller(1, 10, body_url)

Connected to page 1 of https://car-api2.p.rapidapi.com/api/bodies
Connected to page 2 of https://car-api2.p.rapidapi.com/api/bodies
Connected to page 3 of https://car-api2.p.rapidapi.com/api/bodies
Connected to page 4 of https://car-api2.p.rapidapi.com/api/bodies
Connected to page 5 of https://car-api2.p.rapidapi.com/api/bodies
Connected to page 6 of https://car-api2.p.rapidapi.com/api/bodies
Connected to page 7 of https://car-api2.p.rapidapi.com/api/bodies
Connected to page 8 of https://car-api2.p.rapidapi.com/api/bodies
Connected to page 9 of https://car-api2.p.rapidapi.com/api/bodies
Connected to page 10 of https://car-api2.p.rapidapi.com/api/bodies

,id,make_model_trim_id,type,doors,length,width,seats,height,wheel_base,front_track,rear_track,ground_clearance,cargo_capacity,max_cargo_capacity,curb_weight,gross_weight,max_payload,max_towing_capacity,make_model_trim
0,1,1,Hatchback,5,185.8,72.0,5,55.5,107.7,None,None,5.1,24.3,None,3084.0,NaN,NaN,NaN,"{'id': 1, 'make_model_id': 1, 'year': 2023, 'n..."
1,2,2,Hatchback,5,185.8,72.0,5,55.5,107.7,None,None,5.1,24.0,None,3150.0,NaN,NaN,NaN,"{'id': 2, 'make_model_id': 1, 'year': 2023, 'n..."
2,3,3,Hatchback,5,185.8,72.0,5,55.5,107.7,None,None,5.1,24.0,None,3109.0,NaN,NaN,NaN,"{'id': 3, 'make_model_id': 1, 'year': 2023, 'n..."
3,4,4,Hatchback,5,185.8,72.0,5,55.5,107.7,None,None,5.1,24.0,None,3073.0,NaN,NaN,NaN,"{'id': 4, 'make_model_id': 1, 'year': 2023, 'n..."
4,5,5,SUV,5,198.4,78.4,7,67.1,113.8,None,None,7.3,18.1,95.0,4271.0,NaN,NaN,3500.0,"{'id': 5, 'make_model_id': 2, 'year': 2023, 'n..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,996,Truck (Double Cab),4,231.7,81.2,6,75.6,147.5,None,None,7.9,None,None,4693.0,6800.0,2190.0,11600.0,"{'id': 996, 'make_model_id': 164, 'year': 2022..."
996,997,997,Truck (Crew Cab),4,241.2,81.2,6,75.4,157.0,None,None,8.0,None,None,4965.0,7300.0,2000.0,11300.0,"{'id': 997, 'make_model_id': 164, 'year': 2022..."
997,998,998,Truck (Double Cab),4,231.7,81.2,6,75.6,147.5,None,None,7.9,None,None,4720.0,6800.0,2040.0,9700.0,"{'id': 998, 'make_model_id': 164, 'year': 2022..."
998,999,999,Truck (Crew Cab),4,241.2,81.2,6,75.4,157.0,None,None,7.8,None,None,4772.0,6800.0,1960.0,11400.0,"{'id': 999, 'make_model_id': 164, 'year': 2022..."
999,1000,1000,Truck (Crew Cab),4,231.7,81.2,6,75.5,147.4,None,None,8.1,None,None,5090.0,7000.0,2020.0,9500.0,"{'id': 1000, 'make_model_id': 164, 'year': 202..."

### pulling car year / msrp data

In [73]:
trim_url = "https://car-api2.p.rapidapi.com/api/trims"
data_puller(1, 10, trim_url)

Connected to page 1 of https://car-api2.p.rapidapi.com/api/trims
Connected to page 2 of https://car-api2.p.rapidapi.com/api/trims
Connected to page 3 of https://car-api2.p.rapidapi.com/api/trims
Connected to page 4 of https://car-api2.p.rapidapi.com/api/trims
Connected to page 5 of https://car-api2.p.rapidapi.com/api/trims
Connected to page 6 of https://car-api2.p.rapidapi.com/api/trims
Connected to page 7 of https://car-api2.p.rapidapi.com/api/trims
Connected to page 8 of https://car-api2.p.rapidapi.com/api/trims
Connected to page 9 of https://car-api2.p.rapidapi.com/api/trims
Connected to page 10 of https://car-api2.p.rapidapi.com/api/trims

,id,make_model_id,year,name,description,msrp,invoice,created,modified,make_model
0,1,1,2023,Base,4dr Hatchback (1.5L 4cyl Turbo CVT),30800,30055,2022-08-30T22:19:55-04:00,2022-08-30T22:19:55-04:00,"{'id': 1, 'make_id': 1, 'name': 'Integra', 'ma..."
1,2,1,2023,A-Spec,A-Spec 4dr Hatchback w/Technology Package (1.5...,35800,34400,2022-08-30T22:19:55-04:00,2022-08-30T22:19:55-04:00,"{'id': 1, 'make_id': 1, 'name': 'Integra', 'ma..."
2,3,1,2023,A-Spec,A-Spec 4dr Hatchback (1.5L 4cyl Turbo CVT),32800,31524,2022-08-30T22:19:55-04:00,2022-08-30T22:19:55-04:00,"{'id': 1, 'make_id': 1, 'name': 'Integra', 'ma..."
3,4,1,2023,A-Spec,A-Spec 4dr Hatchback w/Technology Package (1.5...,35800,34400,2022-08-30T22:19:55-04:00,2022-08-30T22:19:55-04:00,"{'id': 1, 'make_id': 1, 'name': 'Integra', 'ma..."
4,5,2,2023,Base,4dr SUV (3.5L 6cyl 10A),49050,47815,2022-08-30T22:19:55-04:00,2022-08-30T22:19:55-04:00,"{'id': 2, 'make_id': 1, 'name': 'MDX', 'make':..."
...,...,...,...,...,...,...,...,...,...,...
995,996,164,2022,LT,LT 4dr Double Cab SB (2.7L 4cyl Turbo 8A),41300,38863,2022-08-30T22:20:17-04:00,2022-08-30T22:20:17-04:00,"{'id': 164, 'make_id': 6, 'name': 'Silverado 1..."
996,997,164,2022,LT,LT 4dr Crew Cab 4WD 6.6 ft. SB (2.7L 4cyl Turb...,47300,44509,2022-08-30T22:20:17-04:00,2022-08-30T22:20:17-04:00,"{'id': 164, 'make_id': 6, 'name': 'Silverado 1..."
997,998,164,2022,Work Truck,Work Truck 4dr Double Cab SB (2.7L 4cyl Turbo 8A),34300,32962,2022-08-30T22:20:17-04:00,2022-08-30T22:20:17-04:00,"{'id': 164, 'make_id': 6, 'name': 'Silverado 1..."
998,999,164,2022,LT,LT 4dr Crew Cab 6.6 ft. SB (2.7L 4cyl Turbo 8A),44000,41404,2022-08-30T22:20:17-04:00,2022-08-30T22:20:17-04:00,"{'id': 164, 'make_id': 6, 'name': 'Silverado 1..."
999,1000,164,2022,Work Truck,Work Truck 4dr Crew Cab 4WD 5.8 ft. SB (2.7L 4...,40000,38440,2022-08-30T22:20:17-04:00,2022-08-30T22:20:17-04:00,"{'id': 164, 'make_id': 6, 'name': 'Silverado 1..."